spring:
  cloud:
    gateway:
      routes:
        - id: hello-route
          uri: http://localhost:8081
          predicates:
            - Path=/hello
            - Host=**.example.com
          filters:
            - SetPath=/hello-world

        - id: delayed-route
          uri: http://localhost:8081
          predicates:
            - Path=/delay
            - Host=**.example.com
          filters:
            - SetPath=/delayed
            - AddRequestParameter=delay, 10
