management:
  health:
    redis:
      enabled: true

spring:
  cloud:
    gateway:
      routes:
        - id: hello-route
          uri: http://localhost:8081
          predicates:
            - Path=/hello
            - Host=**.example.com
          filters:
            - SetPath=/hello-world

        - id: delayed-route
          uri: http://localhost:8081
          predicates:
            - Path=/delay
            - Host=**.example.com
          filters:
            - SetPath=/delayed
            - AddRequestParameter=delay, 10
            - name: CircuitBreaker
              args:
                name: customCircuitBreaker
                fallbackUri: forward:/fallback

        - id: rate-limited-route
          uri: http://localhost:8081
          predicates:
            - Path=/uuid
            - Host=**.example.com
          filters:
            - SetPath=/random-uuid
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 2
